#!/bin/bash

# exit 0 if safe to perform actions

mostrecent=$(basename /usr/local/recluse/centos/5/kernel/latest/*.rpm  | awk -F\- '{print $2}')

installed=$(rpm -q "kernel-$mostrecent")

if [ $? -eq 0 ]
then
	exit 1
fi

exit 0
