#!/bin/bash

source /usr/local/recluse/config

hostname=$(hostname | sed -e 's/\..*//')

if [ "$hostname" == "$cluster" ]
then
        list=$(eval echo /usr/local/recluse/centos/$centosversion/forceinstall*/*.rpm)
else
        list=$(eval echo /usr/local/recluse/centos/$centosversion/forceinstall/*.rpm)
fi

for package in $(echo $list)
do
	rpm -ivh $package
done
