#!/bin/bash

source /usr/local/recluse/config

hostname=$(hostname | sed -e 's/\..*//')

if [ "$hostname" == "$cluster" ]
then
	list=$(eval echo /usr/local/recluse/$distro/$distroversion/forceinstall*/*.rpm)
else
	list=$(eval echo /usr/local/recluse/$distro/$distroversion/forceinstall/*.rpm)
fi

for package in $(echo $list)
do
	installed=$(rpm --test -i $package >/dev/null 2>&1)
	if [ $? -eq 0 ]
	then
		exit 0
	fi
done

exit 1
