#!/bin/bash

source /usr/local/recluse/config

hostname=$(hostname | sed -e 's/\..*//')

if [ "$hostname" == "$cluster" ]
then
	list=$(eval echo /usr/local/recluse/centos/$centosversion/forceinstall/*.rpm /usr/local/recluse/centos/$centosversion/forceinstall.head/*.rpm)
else
	list=$(eval echo /usr/local/recluse/centos/$centosversion/forceinstall/*.rpm)
fi

installed=$(rpm --test -i $list >/dev/null 2>&1)

exit $?
