#!/bin/bash

[ -x /usr/bin/yum ] || exit 1
[ -e /var/run/yum.pid ] && exit 1

users=$(whatson -s | wc -l)

if [ $users -eq 0 ]
then
	yum check-update -q > /dev/null
	if [ $? -ne 0 ]
	then
		exit 0
	fi
fi

exit 1
