#!/bin/bash

source /usr/local/recluse/config

[ -x /usr/bin/yum ] || exit 1
[ -e /var/run/yum.pid ] && exit 1

users=$(whatson -s | wc -l)

if [ "$NODE" == "head" ]
then
	yum check-update -q > /dev/null
	if [ $? -ne 0 ]
	then
		exit 0
	fi
else
	if [ $users -eq 0 ]
	then
		yum check-update -q > /dev/null
		if [ $? -ne 0 ]
		then
			exit 0
		fi
	fi
fi

exit 1
