#!/bin/bash

# canupdateinfiniband
#
# check if anyone is using infiniband on a node
#
# Written by Brett Pemberton, brett@vpac.org
# Copyright (C) 2008 Victorian Partnership for Advanced Computing

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

silent=0

if [ "$1" == "-s" ]
then
	silent=1
fi

for user in $(/usr/local/recluse/scripts/bin/whosonnode)
do
	ulist="$ulist -u $user"
done

use=$(lsof $ulist | grep -c /dev/infiniband/)

if [ $use -eq 0 ]
then
	if [ $silent -eq 0 ]
	then
		echo "Nobody using infiniband, will update"
	fi
	exit 0
else
	if [ $silent -eq 0 ]
	then
		echo "Infiniband in use, cancelling update"
	fi
	exit 1
fi
