#!/bin/bash

# canupdatekernel
#
# check if a node needs to be rebooted to a new kernel
#
# Written by Brett Pemberton, brett@vpac.org
# Copyright (C) 2008 Victorian Partnership for Advanced Computing

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

CONFIG=/usr/local/recluse/config
[ -r "$CONFIG" ] || echo "Can't source $CONFIG"
[ -r "$CONFIG" ] || exit 0                     
source $CONFIG

latestkernel=$(basename /usr/local/recluse/$distro/$distroversion/kernel/latest/*.rpm  | awk -F\- '{print $2}')
runningkernel=$(uname -r)
usersonnode=$(/usr/local/recluse/scripts/bin/whosonnode | wc -l)
tmpfs=$(awk '/\/tmp/{print $3}' /proc/mounts)
latesttraceroute=traceroute-2.0.1-3.el5
traceroute=$(rpm -q traceroute)

if [ "$latestkernel" == "$runningkernel" -a "$tmpfs" == "xfs" -a "$latesttraceroute" == "$traceroute" ]
then
	echo -e "\\033[1;33m already running latest kernel, latest CentOS, with xfs /tmp \\033[0;39m"
	exit
fi

if [ $usersonnode -ne 0 ]
then
	echo -e "\\033[1;31m users on node \\033[0;39m"
	exit
fi

echo -e "\\033[1;32m safe to upgrade \\033[0;39m"
