#!/bin/bash

# clean_pbs_directory -- script to clean up pbs while down, and copy undelivered files

# Written by Brett Pemberton, brett@vpac.org
# Copyright (C) 2008 Victorian Partnership for Advanced Computing

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

test=0
running=0
will_delete=0
hostname=$(hostname | sed -e 's/\..*//')
cluster=$(echo $hostname | sed -e 's/[0-9][0-9][0-9]//' -e 's/-m$//')

if [ "$hostname" == "${cluster}-m" ]
then
        echo "Do not run on management node"
        exit
fi

source /etc/init.d/functions

echo "Date: " $(date)

PID=$(pidofproc pbs_mom)
if [ ! -z $PID ]
then
	echo "Mom is running, not touching running jobs"
	running=1
fi

if [ $# -ne 0 ]
then
	test=1
fi

if [ -e /etc/authuser -a $running -eq 0 ]
then
	removelist="/etc/authuser"
	movelist=""
else
	removelist=""
	movelist=""
fi

if [ $running -eq 1 ]
then
	running_job_list=$(/usr/local/sbin/momctl -d0 | awk '/^job.*RUNNING/{print $1}' | sed 's/job\[\(.*\)\]/\1/')
else
	running_job_list=""
fi

for file in $(find /usr/spool/PBS/aux/ -type f -mmin +5)
do
	running=$(echo $running_job_list | grep -c $(basename $file))
	if [ $running -eq 0 ]
	then
		echo "$file is not in running job list, removing"
		removelist="$removelist $file"
		will_delete=1
	fi
done

for file in $(find /usr/spool/PBS/mom_priv/jobs/ -type f -mmin +5)
do
	running=$(echo $running_job_list | grep -c $(basename $file | sed 's/.[A-Z][A-Z]$//'))
	if [ $running -eq 0 ]
	then
		echo "$file is not in running job list, removing"
		removelist="$removelist $file"
		will_delete=1
	fi
done

for file in $(find /usr/spool/PBS/spool/ -type f -mmin +5)
do
	rcp=$(echo $file | grep -c "rcperr")
	if [ $rcp -eq 0 ]
	then
		running=$(echo $running_job_list | grep -c $(basename $file | sed 's/.[A-Z][A-Z]$//'))
		if [ $running -eq 0 ]
		then
			echo "$file is not in running job list, removing"
			movelist="$movelist $file"
			will_delete=1
		fi
	fi
done

for file in $(find /usr/spool/PBS/undelivered/ -type f)
do
	movelist="$movelist $file"
done

if [ $test -eq 1 ]
then
	for file in $(echo $movelist)
	do
		owner=$(stat -c %U $file)
		if [ "$owner" == "UNKNOWN" ]
		then
			removelist="$removelist $file"
			continue
		fi
		dir=$(eval echo ~$owner)
		if [ ! -d $dir/undelivered_output ]
		then
			echo "mkdir $dir/undelivered_output"
			echo "chown $owner $dir/undelivered_output"
		fi
		echo "mv $file $dir/undelivered_output"
	done
	for file in $(echo $removelist)
	do
		echo "rm -f $file"
	done
else
	for file in $(echo $movelist)
	do
		owner=$(stat -c %U $file)
		if [ "$owner" == "UNKNOWN" ]
		then
			removelist="$removelist $file"
			continue
		fi
		dir=$(eval echo ~$owner)
		if [ ! -d $dir/undelivered_output ]
		then
			mkdir -v $dir/undelivered_output
			if [ $? -ne 0 ]
			then
				echo "ERROR: could not mkdir, leaving file $file"
				continue
			fi
			chown -v $owner $dir/undelivered_output
		fi
		mv -v $file $dir/undelivered_output
	done
	for file in $(echo $removelist)
	do
		rm -fv $file
	done
	if [ $will_delete -eq 1 ]
	then
		echo -e "running job list was: \n$running_job_list"
	fi
fi
