#!/bin/bash

# create_torque_cft -- script to create torque config file

# Written by Brett Pemberton, brett@vpac.org
# Copyright (C) 2009 Victorian Partnership for Advanced Computing

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

server=$(cat /usr/spool/PBS/server_name)
host=$(hostname)

echo "SERVERHOST $server" > /usr/spool/PBS/torque.cfg
echo "QSUBHOST $host" >> /usr/spool/PBS/torque.cfg
echo "ALLOWCOMPUTEHOSTSUBMIT true" >> /usr/spool/PBS/torque.cfg
echo "XAUTHPATH /usr/bin/xauth" >> /usr/spool/PBS/torque.cfg
