#!/bin/bash

# removekernels
#
# remove some installed kernels
#
# Written by Brett Pemberton, brett@vpac.org
# Copyright (C) 2007 Victorian Partnership for Advanced Computing

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# remove all kernels, except
#  - most recent
#  - currently running
#  - original centos kernel

CONFIG=/usr/local/recluse/config
[ -r "$CONFIG" ] || echo "Can't source $CONFIG"
[ -r "$CONFIG" ] || exit 0
source $CONFIG

test=0

if [ $# -ne 0 ]
then
	if [ $1 != "test" ]
	then
		test=1
	fi
fi

mostrecent=$(basename /usr/local/recluse/centos/$centosversion/kernel/latest/*.rpm  | awk -F\- '{print $2}')
running=$(uname -r | sed 's/-rc9/rc9/')

for kernel in $(rpm -qa kernel | grep -v "$running-" | grep -v $mostrecent | grep -v ".el5")
do
	echo "will remove $kernel"
	if [ $test -eq 0 ]
	then
		rpm -e $kernel
	fi
done
