#!/bin/bash

# shutdown_all_compute_nodes
#
# shut down and power off all compute nodes in a cluster
#
# Written by Brett Pemberton, brett@vpac.org
# Copyright (C) 2007 Victorian Partnership for Advanced Computing

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

CONFIG=/usr/local/recluse/config
[ -r "$CONFIG" ] || echo "Can't source $CONFIG"
[ -r "$CONFIG" ] || exit 0
source $CONFIG

echo "This will power off all $cluster compute nodes"
echo -n "Are you sure you want to do this? (yes/no): "
read resp

if [ "$resp" != "yes" ]
then
        exit 0
else
        echo "ok then"
fi

echo "powering off linux..."
dsh -f -N compute "poweroff -p"
echo "waiting for shutdown to complete..."
sleep 180
echo "turning off chassis power"
for i in $(seq -w 01 $number_of_compute_nodes); do echo -n "${cluster}0${i}: "; rpower ${cluster}0${i} off; done
echo "should be off now"

