#!/bin/bash

# updatepxe
#
# update node boot image on completed install
#
# Written by Brett Pemberton, brett@vpac.org
# Copyright (C) 2007 Victorian Partnership for Advanced Computing

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

statusdir=/usr/local/recluse/nodestatus/install

while $(/bin/true)
do
	for file in $statusdir/*;
	do
		if [ "$file" != "/usr/local/recluse/nodestatus/install/*" ]
		then
			node=$(host $(basename $file) | awk '{print $5}' | awk -F. '{print $1}')
			status=$(cat $file)
			echo "$node -> $status"

			setboot $node localboot
			rm -f $file
		fi
	done
	sleep 10
done
