#!/bin/bash

source /usr/local/recluse/config

hostname=$(hostname | sed -e 's/\..*//')

if [ "$hostname" == "$cluster" ]
then
        list=$(eval echo /usr/local/recluse/centos/$centosversion/forceupgrade/*.rpm /usr/local/recluse/centos/$centosversion/forceupgrade.head/*.rpm)
else
        list=$(eval echo /usr/local/recluse/centos/$centosversion/forceupgrade/*.rpm)
fi

rpm -Uvh $list

exit $?
