#!/bin/bash

source /usr/local/recluse/config

hostname=$(hostname | sed -e 's/\..*//')

if [ "$hostname" == "$cluster" ]
then
	list=$(eval echo /usr/local/recluse/centos/$centosversion/forceupgrade*/*.rpm)
else
	list=$(eval echo /usr/local/recluse/centos/$centosversion/forceupgrade/*.rpm)
fi

for package in $(echo $list)
do
	upgraded=$(rpm --test -U $package >/dev/null 2>&1)
	if [ $? -eq 0 ]
	then
		exit 0
	fi
done

exit 1
