#!/bin/bash

source /usr/local/recluse/config

hostname=$(hostname | sed -e 's/\..*//')

if [ "$hostname" == "$cluster" ]
then
	list=$(eval echo /usr/local/recluse/centos/$centosversion/forceupgrade/*.rpm /usr/local/recluse/centos/$centosversion/forceupgrade.head/*.rpm)
else
	list=$(eval echo /usr/local/recluse/centos/$centosversion/forceupgrade/*.rpm)
fi

upgraded=$(rpm --test -U $list >/dev/null 2>&1)

exit $?
