#!/bin/bash

ETH_IP=$(ifconfig eth0 | grep "inet addr:" | cut -d: -f 2 | cut -d' ' -f 1)

mkdir /usr/local/recluse/nodestatus/ssh/${ETH_IP}/
cp -vpf /etc/ssh/*key* /usr/local/recluse/nodestatus/ssh/${ETH_IP}/
