#!/bin/bash

[ -e /dev/ipmi0 ] || exit 0
[ -x /usr/bin/ipmitool ] || exit 0

for templabel in $(ipmitool sdr  | grep -v 'ns$' | grep Temp | awk '{print $1 ":" $4}')
do
        label=$(echo $templabel | awk -F: '{print $1}')
	temp=$(echo $templabel | awk -F: '{print $2}')

	if [ $temp -gt 55 ]
	then
		echo "ERROR temperature on $label is $temp"
		exit 1
	fi

done
