#!/bin/bash

CONFIG=/usr/local/recluse/config
[ -r "$CONFIG" ] || echo "Can't source $CONFIG"
[ -r "$CONFIG" ] || exit 0
source $CONFIG

id $user_lookup &>/dev/null;
count=$?

if [ $count -ne 0 ]
then
        echo "ERROR user lookup failed"
        exit 1
fi

