#!/bin/bash

CONFIG=/usr/local/recluse/config
[ -r "$CONFIG" ] || echo "Can't source $CONFIG"
[ -r "$CONFIG" ] || exit 0
source $CONFIG

if test "${HAS_XVFB+set}" = set;
then
        host_xvfb=$HAS_XVFB
else
        host_xvfb=0
fi

if [ $host_xvfb -eq 1 ]
then
        count=$(ps ax | awk '{print $5}' | grep -c "Xvfb$")

        if [ $count -eq 0 ]
        then
                echo "ERROR xvfb not running"
                exit 1
        fi
fi


