#!/bin/bash

# bios_release_date
#
# Extract the bios release date from dmidecode
#
# Written by Brett Pemberton, brett@vpac.org
# Copyright (C) 2009 Victorian Partnership for Advanced Computing

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#/usr/sbin/dmidecode -t 0 | grep Release | awk '{print $3}'
/usr/sbin/dmidecode -s "bios-release-date" | head -1
