#!/bin/bash

# create_authuser

# create an /etc/authuser file from the currently running jobs

# Written by Brett Pemberton (brett@vpac.org)
# Copyright (C) 2009 Victorian Partnership for Advanced Computing

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

touch /etc/authuser.new

for job in $(momctl -d9 | grep RUNNING | awk -F[ '{print $2}' | awk -F] '{print $1}')
do
	qstat -f $job | grep Job_Owner | awk '{print $3}' | awk -F\@ '{print $1}' >> /etc/authuser.new
done

mv -f /etc/authuser.new /etc/authuser
