#!/bin/bash

# sync_dsh_groups
#
# create dsh node groups from moab config
#
# Written by Brett Pemberton, brett@vpac.org
# Copyright (C) 2008 Victorian Partnership for Advanced Computing

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

CONFIG=/usr/local/recluse/config
[ -r "$CONFIG" ] || echo "Can't source $CONFIG"
[ -r "$CONFIG" ] || exit 0
source $CONFIG

DSH_DIR=/usr/local/dsh/node_groups

[ -d $DSH_DIR ] || echo "Directory: $DSH_DIR does not exist"
[ -d $DSH_DIR ] || exit 0

if [ -r /usr/spool/moab/moab-$cluster.cfg ]
then
	MFILE=/usr/spool/moab/moab-$cluster.cfg
elif [ -r /usr/spool/moab/moab.cfg ]
then
	MFILE=/usr/spool/moab/moab.cfg
else
	echo "ERROR: No moab config files found"
	exit
fi

groups=$(egrep "^NODECFG.*PARTITION=" $MFILE | awk -F= '{print $2}' | awk '{print $1}' | sort | uniq)

for group in $(echo $groups)
do
	grep "^NODECFG.*PARTITION=$group$" $MFILE | sed "s/^NODECFG\[\(.*\)\].*PARTITION=$group/\1/" > $DSH_DIR/$group
done
