#!/bin/bash

source /usr/local/recluse/config

if [ -d /usr/local/recluse/centos/$centosversion/kernel.${KERNELTYPE} ]
then
        KERNELDIR="/usr/local/recluse/centos/$centosversion/kernel.${KERNELTYPE}"
else
        KERNELDIR="/usr/local/recluse/centos/$centosversion/kernel"
fi

rpm -ivh $KERNELDIR/latest/*.rpm
