#!/bin/bash

source /usr/local/recluse/config

if [ -d /usr/local/recluse/$distro/$distroversion/kernel.${KERNELTYPE} ]
then
        KERNELDIR="/usr/local/recluse/$distro/$distroversion/kernel.${KERNELTYPE}"
else
        KERNELDIR="/usr/local/recluse/$distro/$distroversion/kernel"
fi

rpm -ivh $KERNELDIR/latest/*.rpm $KERNELDIR/latest/extras.install/*.rpm
rpm -Uvh $KERNELDIR/latest/extras.upgrade/*.rpm

rm -f /etc/upgradekernel
