#!/bin/bash 

source /usr/local/recluse/config

if [ -d /usr/local/recluse/$distro/$distroversion/kernel.${KERNELTYPE} ]
then
        KERNELDIR="/usr/local/recluse/$distro/$distroversion/kernel.${KERNELTYPE}"
else
        KERNELDIR="/usr/local/recluse/$distro/$distroversion/kernel"
fi

if [ -d $KERNELDIR/latest/extras.install ]
then
	extrasi=$(eval echo $KERNELDIR/latest/extras.install/*.rpm)
fi
if [ -d $KERNELDIR/latest/extras.upgrade ]
then
	extrasu=$(eval echo $KERNELDIR/latest/extras.upgrade/*.rpm)
fi

rpm -ivh $KERNELDIR/latest/*.rpm $extrasi

if [ ! -z "$extrasu" ]
then
	rpm --force --replacepkgs -Uvh $extrasu
fi

mostrecent=$(rpm -qp $KERNELDIR/latest/*.rpm --queryformat="%{version}\n")

depmod -a $mostrecent

rm -f /etc/upgradekernel
