#!/bin/bash

source /usr/local/recluse/config

if [ -d /usr/local/recluse/$distro/$distroversion/kernel.${KERNELTYPE} ]
then
	KERNELDIR="/usr/local/recluse/$distro/$distroversion/kernel.${KERNELTYPE}"
else
	KERNELDIR="/usr/local/recluse/$distro/$distroversion/kernel"
fi

if [ ! -e /etc/upgradekernel ]
then
	exit 1
fi

mostrecent=$(rpm -qp $KERNELDIR/latest/*.rpm --queryformat="%{version}-%{release}\n")

installed=$(rpm -q "kernel-$mostrecent")

if [ $? -eq 0 ]
then
	exit 1
fi

installed=$(rpm --test -i $KERNELDIR/latest/*.rpm >/dev/null 2>&1)

exit $?
