#!/bin/bash

source /usr/local/recluse/config

if [ -d /usr/local/recluse/centos/$centosversion/kernel.${KERNELTYPE} ]
then
	KERNELDIR="/usr/local/recluse/centos/$centosversion/kernel.${KERNELTYPE}"
else
	KERNELDIR="/usr/local/recluse/centos/$centosversion/kernel"
fi

mostrecent=$(basename $KERNELDIR/latest/*.rpm  | awk -F\- '{print $2}')

installed=$(rpm -q "kernel-$mostrecent")

if [ $? -eq 0 ]
then
	exit 1
fi

installed=$(rpm --test -i $KERNELDIR/latest/*.rpm >/dev/null 2>&1)

exit $?
