#!/bin/bash

source /usr/local/recluse/config

[[ -e /usr/local/recluse/autoupdates/opensm/hostlist ]] || exit 1

host=$(grep -qc $HOSTNAME /usr/local/recluse/autoupdates/opensm/hostlist)

if [ $? -eq 1 ]
then
	exit 1
fi

exit 0
