#!/bin/bash

# extend_job
#
# extend the life of a PBS job
#
# Written by Brett Pemberton, brett@vpac.org
# Copyright (C) 2008 Victorian Partnership for Advanced Computing

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [ $# -ne 2 ]
then
	echo "usage: $0 <job id> <hours to extend by>"
	exit 1
fi

job=$1
hours=$2

echo "will extend job $job by $hours hours"

if [ ! $hours -gt 0 ]
then
	echo "ERROR: $hours is not a non-zero number"
	exit 1
fi

test=$(qstat -f $job)

if [ $? -ne 0 ]
then
	echo "ERROR: job id: $job is not valid"
	exit 1
fi

walltime=$(qstat -f $job | grep Resource_List.walltime | awk '{print $3}')
new_walltime=$(echo $walltime | awk -v h=$hours -F: '{print $1+h ":" $2 ":" $3}')

echo "old walltime: $walltime"
echo "new walltime: $new_walltime"

qalter -l walltime=$new_walltime $job
