#!/bin/sh

# $Id: qlist,v 1.2 2003/08/01 00:19:23 csamuel Exp $
#
# qlist
#
# Simple script to grab numeric job ID's out of qstat
#
# Written by Chris Samuel <csamuel@vpac.org>
# Copyright (C) 2004 Victorian Partnership for Advanced Computing

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

qstat | egrep  '[0-9:] R ' | awk -F. '{print $1}' | sort -n | uniq
