#!/bin/bash

# rpower
#
# remotely power an ipmi adaptor
#
# Written by Brett Pemberton, brett@vpac.org
# Copyright (C) 2007 Victorian Partnership for Advanced Computing

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

CONFIG=/usr/local/recluse/config
[ -r "$CONFIG" ] || echo "Can't source $CONFIG"
[ -r "$CONFIG" ] || exit 0
source $CONFIG

if [ $# == 0 ]
then
	echo "usage: $0 <node name> <operation>"
	exit
fi

if [ $# == 3 ]
then
	# may have done rpower -n node op ... drop the -n
	shift
fi

node=$1
op=$2

# if they sent an ip address, don't tack on -m

this_cluster=$(echo $node | sed -e 's/[0-9][0-9][0-9]//')

if [ "$this_cluster" == "$cluster" ]
then
	node_mgt=${node}-m
else
	node_mgt=${node}
fi

if [ "$op" == "query" ]
then
	op="status"
fi

if [ "$op" == "reboot" ]
then
	op="reset"
fi

ipmitool -U $ipmi_user -f /etc/ipmi_pass -H $node_mgt power $op
