#!/bin/sh
#

# whatson
#
# print non-system processes on a node
#
# Written by Brett Pemberton, brett@vpac.org
# Copyright (C) 2004 Victorian Partnership for Advanced Computing

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

nh=""

if [ "$1" == "-s" ]
then
	nh="--no-headers"
fi

/bin/ps ax $nh -o pid,user:20,cputime,etime,pmem,pcpu,cmd | awk '{if ($2 != "root" && $2 != "rpc" && $2 != "rpcuser" && $2 != "ntp" && $2 != "xfs" && $2 != "dbus" && $2 != "ganglia" && $2 != "haldaemon" && $2 != "smmsp" ) { print $0 } }'
