#!/bin/bash

host=$(grep -qc $HOSTNAME /usr/local/recluse/centos/5/autoupdates/opensm/hostlist)

if [ $? -eq 1 ]
then
	exit 1
fi

ofedver=$(basename /usr/local/recluse/centos/5/ofed/opensm-latest/opensm-libs*.rpm | sed 's/.*\(ofed.*\).x86_64.rpm/\1/')

installed=$(rpm -q opensm-libs | grep -q "$ofedver")

if [ $? -eq 1 ]
then
	exit 0
fi

exit 1
