#!/bin/bash

source /usr/local/recluse/config

ofedver=$(basename /usr/local/recluse/centos/$centosversion/ofed/latest/mstflint-*.rpm | sed 's/.*\(ofed.*\).x86_64.rpm/\1/')

installed=$(rpm -q libibcommon | grep -q "$ofedver$")

if [ $? -eq 1 ]
then
	/usr/local/recluse/scripts/sbin/canupdateinfiniband -s

	if [ $? -eq 0 ]
	then
		installed=$(rpm --test -i /usr/local/recluse/centos/$centosversion/ofed/latest/*.rpm >/dev/null 2>&1)
		exit $?
	fi

fi

exit 1
