#!/bin/bash

CONFIG=/usr/local/recluse/config
[ -r "$CONFIG" ] || echo "Can't source $CONFIG"
[ -r "$CONFIG" ] || exit 0                     
source $CONFIG

if test "${HAS_OFED+set}" = set;
then
	host_ofed=$HAS_OFED
else
	host_ofed=1
fi

if [ $host_ofed -eq 1 ]
then

	ofedver=$(basename /usr/local/recluse/$distro/$distroversion/ofed/latest/mstflint-*.rpm | sed 's/.*\(ofed.*\).x86_64.rpm/\1/')

	installed=$(rpm -q libibcommon | grep -q "$ofedver$")

	if [ $? -eq 1 ]
	then
		/usr/local/recluse/scripts/sbin/canupdateinfiniband -s

		if [ $? -eq 0 ]
		then
			installed=$(rpm --test -i /usr/local/recluse/$distro/$distroversion/ofed/latest/*.rpm >/dev/null 2>&1)
			exit $?
		fi

	fi

fi

exit 1
